baseURL = 'https://nibtobits.net/'
languageCode = 'en-us'
title = 'nibtobits'
theme = 'etch'
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  dark = "auto"
  highlight = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "now"
    name = "now"
    title = "now"
    url = "/now/"
    weight = 20

# Etch recommends removing the subdirectory for posts in URLs
# https://github.com/LukasJoswiak/etch/wiki/Configuration#sample-configuration
[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allows HTML in Markdown
  unsafe = true